### ISSUE TITLE
Destination not serializable

### ISSUE THREAD

**Issue by amykang2020** [javaee/openmq#382]
_From @glassfishrobot on June 25, 2008 23:47_

Hello,

i try to bind JMS destination into JNDI. This will throw the following exception:

```
java.io.NotSerializableException: com.sun.messaging.jmq.jmsservice.Destination
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1156)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1474)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1392)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1150)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:326)
	at com.sun.enterprise.naming.NamingUtils.makeCopyOfObject(NamingUtils.java:64)
	at
com.sun.enterprise.naming.LocalSerialContextProviderImpl.bind(LocalSerialContextProviderImpl.java:89)
	at com.sun.enterprise.naming.SerialContext.bind(SerialContext.java:461)
	at javax.naming.InitialContext.bind(InitialContext.java:400)
	at
com.macd.research.temporaryqueues.MessageRegistrar.onMessage(MessageRegistrar.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at
com.sun.enterprise.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1067)
	at com.sun.enterprise.security.SecurityUtil.invoke(SecurityUtil.java:176)
	at
com.sun.ejb.containers.BaseContainer.invokeTargetBeanMethod(BaseContainer.java:2895)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:3986)
	at
com.sun.ejb.containers.MessageBeanContainer.deliverMessage(MessageBeanContainer.java:1111)
	at
com.sun.ejb.containers.MessageBeanListenerImpl.deliverMessage(MessageBeanListenerImpl.java:74)
	at
com.sun.enterprise.connectors.inflow.MessageEndpointInvocationHandler.invoke(MessageEndpointInvocationHandler.java:179)
	at $Proxy58.onMessage(Unknown Source)
	at com.sun.messaging.jms.ra.OnMessageRunner.run(OnMessageRunner.java:258)
	at com.sun.enterprise.connectors.work.OneWork.doWork(OneWork.java:76)
	at
com.sun.corba.ee.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:555)
```

Example code:

```
public void onMessage(Message incomingMessage) {
		InitialContext ic;
		try {
			ic = new InitialContext();
			String jndiName = "macd/research/ReplyDestination";
			Destination replyDestination = incomingMessage.getJMSReplyTo();
			if (replyDestination instanceof Serializable) {
				System.out.println("Destination is serializable!");
			} else {
				System.out.println("Destination is NOT serializable!");
			}
			ic.bind(jndiName + "Test", replyDestination);
		} catch (NamingException e) {
			// ignore for testing
		} catch (JMSException e) {
			// ignore for testing
		}
	}
```

But the instanceof operation returns true. So the bind() method tries to
serialize the given object which cause mentioned exception. This happens if JMS
service type is set to "embedded". If i switch the type to "local" everything
works fine. In my opinion there is something wrong ![](https://java.net/jira/images/icons/emoticons/wink.gif). The instanceof operation
should return false if the object is not serializable.
#### Environment
Operating System: All
Platform: Linux
#### Affected Versions
[9.1peur2]

_Copied from original issue: javaee/glassfish#5214_

**Comment by amykang2020** [comment]
_From @glassfishrobot on July 23, 2008 3:56_

@sivakumart said:
Requesting Satish to investigate and fix.

**Comment by amykang2020** [comment]
_From @glassfishrobot on July 23, 2008 4:53_

chrjohn said:
*   *   *   Issue 5214 has been confirmed by votes. ***

**Comment by amykang2020** [comment]
_From @glassfishrobot on September 4, 2008 14:38_

harpreet said:
Marking target milestone as 9.1.1.

**Comment by amykang2020** [comment]
_From @glassfishrobot on September 24, 2008 6:17_

sats said:
Investigating the issue...

**Comment by amykang2020** [comment]
_From @glassfishrobot on October 20, 2008 9:27_

harpreet said:
Please scrub issue and see if it is critical to v2.1.

**Comment by amykang2020** [comment]
_From @glassfishrobot on October 29, 2008 6:13_

sats said:
Downgrading the priority since the problem only exists in the EMBEDDED mode.
This appears to be an issue with the MQ. Will target a fix for the next version
of MQ (4.4).

**Comment by amykang2020** [comment]
_From @glassfishrobot on January 11, 2009 7:1_

sanandal said:
"Reclassifying as P4 because this issue is not deemed "must fix" for this v2.1
release whose primary release driver is SailFin.
This issue will be scrubbed after this release and will be given the right
priority for the next release."

**Comment by amykang2020** [comment]
_From @glassfishrobot on February 14, 2012 6:29_

liang.x.zhao said:
The reason is that although com.sun.messaging.jms.ra.TemporaryQueue is serializable, but it references com.sun.messaging.jmq.jmsservice.Destination which is not serializable.

**Comment by amykang2020** [comment]
_From @glassfishrobot on March 6, 2012 21:56_

tmueller said:
Bulk update to change fix version to "not determined" for all issues still open but with a fix version for a released version.

**Comment by amykang2020** [comment]
_From @glassfishrobot on May 29, 2012 7:26_

liang.x.zhao said:
Nigel,

com.sun.messaging.jms.ra.TemporaryQueue is serializable which is extended from com.sun.messaging.jmq.jmsclient.resources.ClientResources.AdministeredObject, but it indirectly references com.sun.messaging.jmq.jmsservice.Destination (from within its parent class of com.sun.messaging.jms.ra.TemporaryDestination) which is not serializable.

**Comment by amykang2020** [comment]
_From @glassfishrobot on June 25, 2008 23:47_

Was assigned to nigeldeakin

**Comment by amykang2020** [comment]
_From @glassfishrobot on April 20, 2017 17:10_

This issue was imported from java.net JIRA GLASSFISH-5214

**Comment by amykang2020** [comment]
_From @glassfishrobot on June 25, 2008 23:47_

Reported by cplaetzinger

**Comment by amykang2020** [comment]
This is a MQ JMSRA issue in embedded mode

**Comment by amykang2020** [comment]
This is reproduced with latest OpenMQ 5.1.1 + GlassFish 5.0 using test case:

1. A MDB onMessage() unpon receiving first message, send a message with JMSReplyTo set to its listening queue:
[MDBInOutBean]  onMessage(): sent msg with JMSReplyTo: class com.sun.messaging.jmq.jmsclient.TemporaryQueueImpl

2. The MDB onMessage() unpon receiving second message, if JMSReplyTo set,  does the JNDI binding as described in the bug description, it got:

[MDBInOutBean] onMessage():  Destination is serializable!class com.sun.messaging.jms.ra.TemporaryQueue]]

[2017-06-26T12:21:21.567-0700] [glassfish 5.0] [SEVERE] [AS-NAMING-00006] [org.glassfish.naming] [tid: _ThreadID=107 _ThreadName=p: thread-pool-1; w: 5] [timeMillis: 1498504881567] [levelValue: 1000] [[
  Exception in NamingManagerImpl copyMutableObject(): {0}
java.io.NotSerializableException: com.sun.messaging.jmq.jmsservice.Destination
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at com.sun.enterprise.naming.util.NamingUtilsImpl.makeCopyOfObject(NamingUtilsImpl.java:114)
        at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.bind(LocalSerialContextProviderImpl.java:93)
        at com.sun.enterprise.naming.impl.SerialContext.bind(SerialContext.java:640)
        at javax.naming.InitialContext.bind(InitialContext.java:425)
        at javax.naming.InitialContext.bind(InitialContext.java:425)
        at test.jmsclient.appserver.mdb_inout.MDBInOutBean.onMessage(Unknown Source)
