### ISSUE TITLE
Thread deadlock in JMS broker

### ISSUE THREAD

**Issue by amykang2020** [javaee/openmq#384]
_From @glassfishrobot on September 3, 2014 18:49_

We have run into a thread deadlock issue with one of our applications running on Glassfish 4 / MQ 5.0\. It appears that the issue is caused by the message queue broker, so please let me know if this is not the right location to file this issue.

The scenario is as follows:

*   Broker is running locally with a single message queue set to FLOW_CONTROL
*   Application contains multiple producers, each within their own session, for said queue. These producers have different life-cycles, some being kept alive for the duration of the application, some being created and closed more frequently.
*   MDBs are used to consume messages from the queue

Under load, we see that after some time both the producer as well as the consumer side in our application start outputting messages that indicate that the broker is no longer responding:
[2014-09-03T03:46:15.339+0200] [glassfish 4.0] [WARNING] [] [javax.jms.connection] [tid: _ThreadID=411 _ThreadName=p: thread-pool-1; w: 111] [timeMillis: 1409708775339] [levelValue: 900] [[
[W2003]: Broker not responding [ACKNOWLEDGE(24)] for 1800 seconds. Still trying..., broker addr=localhost:7677(33136), connectionID=7124211059811362560, clientID=null, consumerID=14551566]]

It is however still possible to connect to the broker using imqcmd.

A thread dump of the broker shows the following:
Found one Java-level deadlock:
=============================
"Thread-jms[271]":
waiting to lock monitor 0x000000001366adc8 (object 0x00000000c01f94a8, a com.sun.messaging.jmq.jmsserver.core.Destination$ProducerFlow),
which is held by "Thread-jms[144]"
"Thread-jms[144]":
waiting to lock monitor 0x0000000013b81488 (object 0x00000000c0880b90, a com.sun.messaging.jmq.jmsserver.core.Producer),
which is held by "Thread-jms[271]"

Java stack information for the threads listed above:
===================================================
"Thread-jms[271]":
at com.sun.messaging.jmq.jmsserver.core.Destination$ProducerFlow.removeProducer(Destination.java:4951)

*   waiting to lock <0x00000000c01f94a8> (a com.sun.messaging.jmq.jmsserver.core.Destination$ProducerFlow)
    at com.sun.messaging.jmq.jmsserver.core.Destination.removeProducer(Destination.java:3670)
    at com.sun.messaging.jmq.jmsserver.core.Producer.destroyProducer(Producer.java:119)
*   locked <0x00000000c0880b90> (a com.sun.messaging.jmq.jmsserver.core.Producer)
    at com.sun.messaging.jmq.jmsserver.plugin.spi.ProducerSpi.destroyProducer(ProducerSpi.java:250)
    at com.sun.messaging.jmq.jmsserver.core.CoreLifecycleImpl.destroyProducer(CoreLifecycleImpl.java:347)
    at com.sun.messaging.jmq.jmsserver.service.imq.IMQConnection.removeProducer(IMQConnection.java:781)
    at com.sun.messaging.jmq.jmsserver.data.handlers.ProducerHandler.removeProducer(ProducerHandler.java:341)
    at com.sun.messaging.jmq.jmsserver.data.handlers.ProducerHandler.handle(ProducerHandler.java:214)
    at com.sun.messaging.jmq.jmsserver.data.PacketRouter.handleMessage(PacketRouter.java:199)
    at com.sun.messaging.jmq.jmsserver.service.imq.IMQIPConnection.readData(IMQIPConnection.java:1320)
    at com.sun.messaging.jmq.jmsserver.service.imq.IMQIPConnection.process(IMQIPConnection.java:553)
    at com.sun.messaging.jmq.jmsserver.service.imq.OperationRunnable.process(OperationRunnable.java:176)
    at com.sun.messaging.jmq.jmsserver.pool.BasicRunnable.run(BasicRunnable.java:499)
    at java.lang.Thread.run(Thread.java:744)
    "Thread-jms[144]":
    at com.sun.messaging.jmq.jmsserver.plugin.spi.ProducerSpi.isValid(ProducerSpi.java:261)
*   waiting to lock <0x00000000c0880b90> (a com.sun.messaging.jmq.jmsserver.core.Producer)
    at com.sun.messaging.jmq.jmsserver.core.Destination$ProducerFlow.checkResumeFlow(Destination.java:4879)
*   locked <0x00000000c01f94a8> (a com.sun.messaging.jmq.jmsserver.core.Destination$ProducerFlow)
*   locked <0x00000000c01f8db0> (a com.sun.messaging.jmq.util.lists.SimpleNFLHashMap)
    at com.sun.messaging.jmq.jmsserver.core.Destination$ProducerFlow.checkResumeFlow(Destination.java:4790)
    at com.sun.messaging.jmq.jmsserver.core.Destination.removeProducer(Destination.java:3671)
    at com.sun.messaging.jmq.jmsserver.core.Producer.destroyProducer(Producer.java:119)
*   locked <0x00000000c08a02d8> (a com.sun.messaging.jmq.jmsserver.core.Producer)
    at com.sun.messaging.jmq.jmsserver.plugin.spi.ProducerSpi.destroyProducer(ProducerSpi.java:250)
    at com.sun.messaging.jmq.jmsserver.core.CoreLifecycleImpl.destroyProducer(CoreLifecycleImpl.java:347)
    at com.sun.messaging.jmq.jmsserver.service.imq.IMQConnection.removeProducer(IMQConnection.java:781)
    at com.sun.messaging.jmq.jmsserver.data.handlers.ProducerHandler.removeProducer(ProducerHandler.java:341)
    at com.sun.messaging.jmq.jmsserver.data.handlers.ProducerHandler.handle(ProducerHandler.java:214)
    at com.sun.messaging.jmq.jmsserver.data.PacketRouter.handleMessage(PacketRouter.java:199)
    at com.sun.messaging.jmq.jmsserver.service.imq.IMQIPConnection.readData(IMQIPConnection.java:1320)
    at com.sun.messaging.jmq.jmsserver.service.imq.IMQIPConnection.process(IMQIPConnection.java:553)
    at com.sun.messaging.jmq.jmsserver.service.imq.OperationRunnable.process(OperationRunnable.java:176)
    at com.sun.messaging.jmq.jmsserver.pool.BasicRunnable.run(BasicRunnable.java:499)
    at java.lang.Thread.run(Thread.java:744)

Found 1 deadlock.

Looking at the source for OpenMQ 5.0, there seems to be a race condition to acquire a lock on a producer. As best as I understand, the scenario is as follows:

Request to destroy Producer A locks A
Request to destroy Producer B locks B
Destination locks flow control to destroy A
Destination waits for lock on flow control to destroy B
Destination for A attempts to acquire lock for producer B (synchronized call to Producer.isValid)
#### Environment
Linux
#### Affected Versions
[4.0]

_Copied from original issue: javaee/glassfish#21182_

**Comment by amykang2020** [comment]
_From @glassfishrobot on March 27, 2017 21:8_

mreichman said:
I am seeing a similar scenario, using the MQ 5.1.1 bundled with Payara 4.1.1.171\. Under some load, in a pattern which worked without issue under GF 3.1.2 and its broker, I am seeing a deadlock in the MQ process. I've seen it in as little as 40-50m, and as much as 7 hours. It seems to be exacerbated by the number of producers. If I can limit the number of producers, it seems less likely to happen.

My case is in Windows Server 2008 R2, with JDK 8u121, using the Payara 4.1.1.171 zip distribution of Glassfish, with the JMS broker running in FLOW_CONTROL mode, with a 1GB heap, and the default max of 100K messages for this particular queue.

I'm attaching three logs:
server.log - Glassfish log, the issues start around the 7h mark, on line 771
[https://paste.ee/p/kEmJO](https://paste.ee/p/kEmJO)

log.txt - OpenMQ log
[https://paste.ee/p/9drCs](https://paste.ee/p/9drCs)

jmq-lock.txt - jstack output showing the same deadlock as the original poster.
[https://paste.ee/p/iZmwf](https://paste.ee/p/iZmwf)

This is inhibiting our ability to move from GF 3.x to GF 4.x.

**Comment by amykang2020** [comment]
_From @glassfishrobot on March 28, 2017 13:6_

mreichman said:
I filed this in a more appropriate place: [https://java.net/jira/browse/MQ-378](https://java.net/jira/browse/MQ-378)

**Comment by amykang2020** [comment]
_From @glassfishrobot on September 3, 2014 18:49_

Was assigned to liang.x.zhao

**Comment by amykang2020** [comment]
_From @glassfishrobot on April 21, 2017 8:35_

This issue was imported from java.net JIRA GLASSFISH-21182

**Comment by amykang2020** [comment]
_From @glassfishrobot on September 3, 2014 18:49_

Reported by bdamer

**Comment by amykang2020** [comment]
The deadlock occurs when 2 producer instances on the same destination closing at about same time:
Thread1:
Producer1.destroyProducer()  Producer1 lock -> Destination.removeProducer() ->
      Destionation.ProducerFlow.removeProducer() ProducerFlow lock ->
                                                                  Producer1.destroy() Producer1 lock
      Destination.Producerflow.checkResumeFlow() ->
              destMessages lock ->  waiting Producer2.isValid() Producer2 lock
Thread2:
Producer2.destroyProducer()  Producer2 lock -> Destination.removeProducer() ->
      Destionation.ProducerFlow.removeProducer() waiting ProducerFlow lock
